export enum AuthEnum {
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_ERROR = "LOGIN_ERROR",

  SIGNUP_REQUEST = "SIGNUP_REQUEST",
  SIGNUP_ERROR = "SIGNUP_ERROR",
  SIGNUP_SUCCESS = "SIGNUP_SUCCESS",

  LOAD_USER_REQUEST = "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS",
  LOAD_USER_ERROR = "LOAD_USER_ERROR",

  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
}

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_ERROR = "LOAD_USER_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
